
project_id = "lfpmxqcqygujcftysbtu"
[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[storage]
enabled = true

[realtime]
enabled = true

[functions.enhance-resume]
verify_jwt = true

[functions.ats-analysis]
verify_jwt = true

[functions.parse-resume]
verify_jwt = true

[functions.create-resume]
verify_jwt = true

