version = 0.1

[default]
[default.global]
[default.global.parameters]
stack_name = "Mockinterview4u"
region = "us-east-1"

[default.build]
[default.build.parameters]
cached = true
parallel = true

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
resolve_s3 = true
parameter_overrides = [
    "CorsOrigins=http://localhost:5173,http://localhost:3000,http://localhost:8080,http://localhost:8081",
    "OpenAIApiKey=${OPENAI_API_KEY}",
    "AdobeClientId=${ADOBE_CLIENT_ID}",
    "AdobeClientSecret=${ADOBE_CLIENT_SECRET}",
    "SupabaseUrl=${SUPABASE_URL}",
    "SupabaseServiceRoleKey=${SUPABASE_SERVICE_ROLE_KEY}"
] 